# tests/conftest.py
"""Pytest fixtures: minimal synthetic EPUBs and temp vaults."""
from pathlib import Path
import zipfile

import pytest


MIMETYPE = "application/epub+zip"

CONTAINER_XML = """<?xml version="1.0"?>
<container version="1.0" xmlns="urn:oasis:names:tc:opendocument:xmlns:container">
  <rootfiles>
    <rootfile full-path="OEBPS/content.opf" media-type="application/oebps-package+xml"/>
  </rootfiles>
</container>
"""

CONTENT_OPF_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<package xmlns="http://www.idpf.org/2007/opf" version="2.0" unique-identifier="BookId">
  <metadata xmlns:dc="http://purl.org/dc/elements/1.1/">
    <dc:title>{title}</dc:title>
    <dc:creator>{author}</dc:creator>
    <dc:date>{year}</dc:date>
    <dc:identifier id="BookId">urn:uuid:test-{title_slug}</dc:identifier>
    <dc:language>en</dc:language>
{extra_metadata}
  </metadata>
  <manifest>
    <item id="ncx" href="toc.ncx" media-type="application/x-dtbncx+xml"/>
{manifest_items}
  </manifest>
  <spine toc="ncx">
{spine_items}
  </spine>
</package>
"""

NCX_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<ncx xmlns="http://www.daisy.org/z3986/2005/ncx/" version="2005-1">
  <head><meta name="dtb:uid" content="urn:uuid:test"/></head>
  <docTitle><text>{title}</text></docTitle>
  <navMap>
{nav_points}
  </navMap>
</ncx>
"""

NAV_POINT_TEMPLATE = """    <navPoint id="{id}" playOrder="{order}">
      <navLabel><text>{label}</text></navLabel>
      <content src="{src}"/>
    </navPoint>"""

HTML_TEMPLATE = """<?xml version="1.0" encoding="utf-8"?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head><title>{title}</title></head>
<body>
<h1>{title}</h1>
<p>{body}</p>
</body>
</html>
"""


def _build_epub(
    out_path: Path,
    title: str,
    author: str,
    year: str,
    sections: list[tuple[str, str]],  # [(section_label, body_text), ...]
    extra_metadata: str = "",
) -> Path:
    """Build a minimal valid EPUB at out_path."""
    title_slug = title.lower().replace(" ", "-")
    manifest_items = []
    spine_items = []
    nav_points = []
    html_files = {}
    for i, (label, body) in enumerate(sections, start=1):
        item_id = f"s{i}"
        href = f"section-{i}.xhtml"
        manifest_items.append(f'    <item id="{item_id}" href="{href}" media-type="application/xhtml+xml"/>')
        spine_items.append(f'    <itemref idref="{item_id}"/>')
        nav_points.append(NAV_POINT_TEMPLATE.format(id=item_id, order=i, label=label, src=href))
        html_files[href] = HTML_TEMPLATE.format(title=label, body=body)

    content_opf = CONTENT_OPF_TEMPLATE.format(
        title=title,
        author=author,
        year=year,
        title_slug=title_slug,
        manifest_items="\n".join(manifest_items),
        spine_items="\n".join(spine_items),
        extra_metadata=extra_metadata,
    )
    ncx = NCX_TEMPLATE.format(title=title, nav_points="\n".join(nav_points))

    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
        # mimetype must be first and uncompressed per EPUB spec
        zf.writestr("mimetype", MIMETYPE, compress_type=zipfile.ZIP_STORED)
        zf.writestr("META-INF/container.xml", CONTAINER_XML)
        zf.writestr("OEBPS/content.opf", content_opf)
        zf.writestr("OEBPS/toc.ncx", ncx)
        for href, html in html_files.items():
            zf.writestr(f"OEBPS/{href}", html)

    return out_path


@pytest.fixture
def normal_epub(tmp_path: Path) -> Path:
    """A properly-structured EPUB with 3 chapters + front/back matter."""
    out = tmp_path / "normal.epub"
    sections = [
        ("Cover", "Cover image placeholder."),
        ("Title Page", "Title page."),
        ("Chapter 1: Origins", "The first chapter talks about origins. " * 40),
        ("Chapter 2: Growth", "The second chapter talks about growth. " * 40),
        ("Chapter 3: Reflection", "The third chapter reflects. " * 40),
        ("Notes", "Reference notes."),
        ("Copyright", "(c) Test Author."),
    ]
    return _build_epub(out, title="The Test Book", author="Test Author", year="2024", sections=sections)


@pytest.fixture
def pdf_origin_epub(tmp_path: Path) -> Path:
    """A PDF-origin EPUB detectable via generator metadata."""
    out = tmp_path / "pdf_origin.epub"
    sections = [
        ("Cover", "<p>Generated by pdftohtml 0.36</p>"),
        ("Content", "Wall of text with no real chapter boundaries. " * 200),
    ]
    extra = '    <meta name="generator" content="pdftohtml 0.36"/>'
    return _build_epub(
        out,
        title="PDF Origin Book",
        author="Ghost Author",
        year="2020",
        sections=sections,
        extra_metadata=extra,
    )


@pytest.fixture
def tmp_vault(tmp_path: Path) -> Path:
    """An empty tmp dir to use as a vault root."""
    v = tmp_path / "book summaries"
    v.mkdir()
    return v
