"""Obsidian LLM-wiki vault writer: bootstrap, collected.md, analysis_queue.md, raw/books."""
from __future__ import annotations

import datetime as dt
import re
import shutil
from pathlib import Path


SCHEMA_TEMPLATE = """# Wiki Schema — Book Summaries

> Generated by book-summarizer on {date}. Edit freely; the /summarize-book
> slash command reads this file to know your conventions, but only updates
> index.md and log.md automatically. The tag taxonomy below is the contract:
> new tags must be added here BEFORE being used on a page.

## Domain

This wiki covers **books**: analyzed book summaries and the entities
(people, organizations, studies, products) and concepts (ideas, mechanisms,
frameworks) they cite, plus cross-book comparisons and verify queries.

## Conventions

- File names: `<Title> - <Author>.md` for books. Entities and concepts use
  their own names (`Jim Collins.md`, `flywheel effect.md`). Comparisons use
  `<slug> - contradiction.md`.
- Every wiki page starts with YAML frontmatter.
- Use `[[wikilinks]]` to link between pages.
- Book summaries must link to every entity/concept page they touch.
- Entity/concept pages back-link to every book that cited them.
- Bump the `updated` date when a page is modified.
- Every new page must be added to index.md under the correct section.
- Every analyze action is appended to log.md.

## Frontmatter (book page)

```yaml
---
title: <Book Title>
author: <Author Name>
year: <Publication Year>
created: YYYY-MM-DD
updated: YYYY-MM-DD
type: book
tags: [from taxonomy below]
raw_path: raw/books/<Title> - <Author>.md
isbn: <if available>
pages: <if available>
summary_mode: map-reduce | single-pass
lens: <lens name>
---
```

## Tag Taxonomy

- genre: non-fiction, fiction, self-help, business, philosophy, memoir, biography, science, history
- meta: contradiction, controversy, weak-claim, unverified, verified, critical-pass

## Page Creation Thresholds

- **Create an entity/concept page** when mentioned in 2+ books OR central to one.
- **Add to existing page** when a new book mentions it.
- **DON'T create a page** for passing mentions.
- **Split a page** when it exceeds ~200 lines.

## Update Policy

When new information conflicts with existing content:
1. Check publication dates — newer books do not automatically supersede older
   ones (philosophy is not chronology).
2. If genuinely contradictory, note both positions with wikilinks and create a
   `comparisons/<slug> - contradiction.md` page.
3. Flag for user review in the next analyze run.
"""

INDEX_TEMPLATE = """# Index — Book Summaries

## By Author

_(populated by /summarize-book)_

## By Topic

_(populated by /summarize-book)_

## By Date Analyzed

_(populated by /summarize-book)_
"""

LOG_TEMPLATE = """# Action Log

> Append-only. Every /summarize-book run adds an entry.

"""

COLLECTED_HEADER = """# Collected Books

> One row per ingested book. Edit with /summarize-book or via CLI.

| Title | Author | Status | Chapters | Conversion | Mode | Lens | Analyzed At | Source |
|---|---|---|---|---|---|---|---|---|
"""

ANALYSIS_QUEUE_HEADER = """# Analysis Queue

> Oldest-first. /summarize-book pops from here.

"""


def bootstrap_vault(vault_path: Path) -> None:
    """Ensure vault folder structure and index files exist. Idempotent."""
    vault_path = Path(vault_path)
    vault_path.mkdir(parents=True, exist_ok=True)

    for sub in ("raw/books", "books", "entities", "concepts", "comparisons", "queries"):
        (vault_path / sub).mkdir(parents=True, exist_ok=True)

    today = dt.date.today().isoformat()
    # Use string replace instead of .format() to avoid issues with literal braces in YAML examples
    schema_content = SCHEMA_TEMPLATE.replace("{date}", today)

    defaults = [
        ("SCHEMA.md", schema_content),
        ("index.md", INDEX_TEMPLATE),
        ("log.md", LOG_TEMPLATE),
        ("collected.md", COLLECTED_HEADER),
        ("analysis_queue.md", ANALYSIS_QUEUE_HEADER),
    ]
    for name, content in defaults:
        p = vault_path / name
        if not p.exists():
            p.write_text(content)


def _safe_filename(s: str) -> str:
    """Replace filesystem-unsafe characters for Obsidian compatibility.

    Obsidian supports almost everything, but we normalize anyway:
      - colon, slash, backslash, question mark, asterisk, less/greater, pipe → underscore
      - strip leading/trailing whitespace
    """
    s = s.strip()
    return re.sub(r'[:\\/?*<>|"]', "_", s)


def raw_book_path(vault_path: Path, title: str, author: str) -> Path:
    """Canonical raw/books/<Title> - <Author>.md path."""
    safe_title = _safe_filename(title)
    safe_author = _safe_filename(author) if author else "Unknown"
    return Path(vault_path) / "raw" / "books" / f"{safe_title} - {safe_author}.md"


def write_raw_book(
    vault_path: Path,
    title: str,
    author: str,
    source_markdown_path: Path | None,
    content: str | None = None,
) -> Path:
    """Write the raw chapter-structured markdown for a book.

    Either provide `source_markdown_path` (copied) or `content` (written directly).
    """
    dest = raw_book_path(vault_path, title, author)
    dest.parent.mkdir(parents=True, exist_ok=True)
    if source_markdown_path is not None and content is not None:
        raise ValueError("Provide source_markdown_path OR content, not both")
    if source_markdown_path is not None:
        shutil.copyfile(source_markdown_path, dest)
    elif content is not None:
        dest.write_text(content)
    else:
        raise ValueError("Provide source_markdown_path OR content")
    return dest
