"""Obsidian LLM-wiki vault writer: bootstrap, collected.md, analysis_queue.md, raw/books."""
from __future__ import annotations

import datetime as dt
import re
import shutil
from dataclasses import dataclass
from pathlib import Path


SCHEMA_TEMPLATE = """# Wiki Schema — Book Summaries

> Generated by book-llm-wiki on {date}. Edit freely; the /summarize-book
> slash command reads this file to know your conventions, but only updates
> index.md and log.md automatically. The tag taxonomy below is the contract:
> new tags must be added here BEFORE being used on a page.

## Domain

This wiki covers **books**: analyzed book summaries and the entities
(people, organizations, studies, products) and concepts (ideas, mechanisms,
frameworks) they cite, plus cross-book comparisons and verify queries.

## Conventions

- File names: `<Title> - <Author>.md` for books. Entities and concepts use
  their own names (`Jim Collins.md`, `flywheel effect.md`). Comparisons use
  `<slug> - contradiction.md`.
- Every wiki page starts with YAML frontmatter.
- Use `[[wikilinks]]` to link between pages.
- Book summaries must link to every entity/concept page they touch.
- Entity/concept pages back-link to every book that cited them.
- Bump the `updated` date when a page is modified.
- Every new page must be added to index.md under the correct section.
- Every analyze action is appended to log.md.

## Frontmatter (book page)

```yaml
---
title: <Book Title>
author: <Author Name>
year: <Publication Year>
created: YYYY-MM-DD
updated: YYYY-MM-DD
type: book
tags: [from taxonomy below]
raw_path: raw/books/<Title> - <Author>.md
isbn: <if available>
pages: <if available>
summary_mode: map-reduce | single-pass
lens: <lens name>
---
```

## Tag Taxonomy

- genre: non-fiction, fiction, self-help, business, philosophy, memoir, biography, science, history
- meta: contradiction, controversy, weak-claim, unverified, verified, critical-pass

## Page Creation Thresholds

- **Create an entity/concept page** when mentioned in 2+ books OR central to one.
- **Add to existing page** when a new book mentions it.
- **DON'T create a page** for passing mentions.
- **Split a page** when it exceeds ~200 lines.

## Update Policy

When new information conflicts with existing content:
1. Check publication dates — newer books do not automatically supersede older
   ones (philosophy is not chronology).
2. If genuinely contradictory, note both positions with wikilinks and create a
   `comparisons/<slug> - contradiction.md` page.
3. Flag for user review in the next analyze run.
"""

INDEX_TEMPLATE = """# Index — Book Summaries

## By Author

_(populated by /summarize-book)_

## By Topic

_(populated by /summarize-book)_

## By Date Analyzed

_(populated by /summarize-book)_
"""

LOG_TEMPLATE = """# Action Log

> Append-only. Every /summarize-book run adds an entry.

"""

COLLECTED_HEADER = """# Collected Books

> One row per ingested book. Edit with /summarize-book or via CLI.

| Title | Author | Status | Chapters | Conversion | Mode | Lens | Analyzed At | Source |
|---|---|---|---|---|---|---|---|---|
"""

ANALYSIS_QUEUE_HEADER = """# Analysis Queue

> Oldest-first. /summarize-book pops from here.

"""


def bootstrap_vault(vault_path: Path) -> None:
    """Ensure vault folder structure and index files exist. Idempotent."""
    vault_path = Path(vault_path)
    vault_path.mkdir(parents=True, exist_ok=True)

    for sub in ("raw/books", "books", "entities", "concepts", "comparisons", "queries"):
        (vault_path / sub).mkdir(parents=True, exist_ok=True)

    today = dt.date.today().isoformat()
    # Use string replace instead of .format() to avoid issues with literal braces in YAML examples
    schema_content = SCHEMA_TEMPLATE.replace("{date}", today)

    defaults = [
        ("SCHEMA.md", schema_content),
        ("index.md", INDEX_TEMPLATE),
        ("log.md", LOG_TEMPLATE),
        ("collected.md", COLLECTED_HEADER),
        ("analysis_queue.md", ANALYSIS_QUEUE_HEADER),
    ]
    for name, content in defaults:
        p = vault_path / name
        if not p.exists():
            p.write_text(content)


def _safe_filename(s: str) -> str:
    """Replace filesystem-unsafe characters for Obsidian compatibility.

    Obsidian supports almost everything, but we normalize anyway:
      - colon, slash, backslash, question mark, asterisk, less/greater, pipe → underscore
      - strip leading/trailing whitespace
    """
    s = s.strip()
    return re.sub(r'[:\\/?*<>|"]', "_", s)


def raw_book_path(vault_path: Path, title: str, author: str) -> Path:
    """Canonical raw/books/<Title> - <Author>/<Title> - <Author>.md path.

    Each book lives in its own subdirectory so converter-emitted images
    (referenced as `./images/foo.jpg` in the markdown) resolve correctly
    and don't collide across books.
    """
    safe_title = _safe_filename(title)
    safe_author = _safe_filename(author) if author else "Unknown"
    stem = f"{safe_title} - {safe_author}"
    return Path(vault_path) / "raw" / "books" / stem / f"{stem}.md"


def write_raw_book(
    vault_path: Path,
    title: str,
    author: str,
    source_markdown_path: Path | None,
    content: str | None = None,
) -> Path:
    """Write the raw chapter-structured markdown for a book.

    Either provide `source_markdown_path` (copied) or `content` (written directly).
    """
    dest = raw_book_path(vault_path, title, author)
    dest.parent.mkdir(parents=True, exist_ok=True)
    if source_markdown_path is not None and content is not None:
        raise ValueError("Provide source_markdown_path OR content, not both")
    if source_markdown_path is not None:
        shutil.copyfile(source_markdown_path, dest)
    elif content is not None:
        dest.write_text(content)
    else:
        raise ValueError("Provide source_markdown_path OR content")
    return dest


@dataclass
class CollectedRow:
    title: str
    author: str
    status: str            # 'queued' | 'analyzed' | 'failed'
    chapters: int
    conversion_quality: str  # 'high' | 'low'
    mode: str              # 'structured' | 'flat'
    lens: str              # '' when not yet analyzed
    analyzed_at: str       # '' when not yet analyzed
    source: str            # absolute source path

    def to_row(self) -> str:
        cols = [
            self.title,
            self.author,
            self.status,
            str(self.chapters),
            self.conversion_quality,
            self.mode,
            self.lens,
            self.analyzed_at,
            self.source,
        ]
        # Escape pipes in cell values to avoid breaking markdown table
        cols = [c.replace("|", "\\|") for c in cols]
        return "| " + " | ".join(cols) + " |"


def append_collected_row(vault_path: Path, row: CollectedRow) -> None:
    collected = Path(vault_path) / "collected.md"
    if not collected.exists():
        collected.write_text(COLLECTED_HEADER)
    with collected.open("a") as fh:
        fh.write(row.to_row() + "\n")


def _read_collected_rows(vault_path: Path) -> list[dict]:
    collected = Path(vault_path) / "collected.md"
    if not collected.exists():
        return []
    rows = []
    header_passed = False
    for line in collected.read_text().splitlines():
        if line.startswith("|---"):
            header_passed = True
            continue
        if not header_passed:
            continue
        if not line.startswith("|"):
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) < 9:
            continue
        rows.append({
            "title": cells[0],
            "author": cells[1],
            "status": cells[2],
            "chapters": cells[3],
            "conversion_quality": cells[4],
            "mode": cells[5],
            "lens": cells[6],
            "analyzed_at": cells[7],
            "source": cells[8],
        })
    return rows


def is_ingested(vault_path: Path, title: str, author: str) -> bool:
    for row in _read_collected_rows(vault_path):
        if row["title"] == title and row["author"] == author:
            return True
    return False


def _write_collected_rows(vault_path: Path, rows: list[dict]) -> None:
    collected = Path(vault_path) / "collected.md"
    lines = [COLLECTED_HEADER.rstrip() + "\n"]
    for r in rows:
        cells = [r["title"], r["author"], r["status"], r["chapters"],
                 r["conversion_quality"], r["mode"], r["lens"],
                 r["analyzed_at"], r["source"]]
        cells = [c.replace("|", "\\|") for c in cells]
        lines.append("| " + " | ".join(cells) + " |\n")
    collected.write_text("".join(lines))


def remove_collected_rows(vault_path: Path, title: str, author: str | None) -> int:
    """Remove all collected.md rows matching title (and author, if given). Returns count removed."""
    rows = _read_collected_rows(vault_path)
    keep, removed = [], 0
    for r in rows:
        if r["title"] == title and (author is None or r["author"] == author):
            removed += 1
            continue
        keep.append(r)
    if removed:
        _write_collected_rows(vault_path, keep)
    return removed


def remove_from_queue(vault_path: Path, title: str, author: str | None) -> int:
    """Remove all analysis_queue.md entries matching title (and author, if given)."""
    q_file = Path(vault_path) / "analysis_queue.md"
    if not q_file.exists():
        return 0
    lines = q_file.read_text().splitlines(keepends=True)
    out, removed = [], 0
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("- ") and " - " in stripped[2:]:
            entry = stripped[2:].strip()
            t, a = entry.split(" - ", 1)
            if t.strip() == title and (author is None or a.strip() == author):
                removed += 1
                continue
        out.append(line)
    if removed:
        q_file.write_text("".join(out))
    return removed


def delete_raw_book(vault_path: Path, title: str, author: str) -> bool:
    """Delete the raw/books/<Title> - <Author>/ directory. Returns True if deleted."""
    raw_dir = raw_book_path(vault_path, title, author).parent
    if raw_dir.exists():
        shutil.rmtree(raw_dir)
        return True
    return False


def read_queue(vault_path: Path) -> list[dict]:
    q_file = Path(vault_path) / "analysis_queue.md"
    if not q_file.exists():
        return []
    out = []
    for line in q_file.read_text().splitlines():
        if line.startswith("- "):
            entry = line[2:].strip()
            # Format: "Title - Author"
            if " - " in entry:
                title, author = entry.split(" - ", 1)
                out.append({"title": title.strip(), "author": author.strip()})
    return out


def enqueue_for_analysis(vault_path: Path, title: str, author: str) -> None:
    existing = read_queue(vault_path)
    for row in existing:
        if row["title"] == title and row["author"] == author:
            return  # already queued
    q_file = Path(vault_path) / "analysis_queue.md"
    if not q_file.exists():
        q_file.write_text(ANALYSIS_QUEUE_HEADER)
    with q_file.open("a") as fh:
        fh.write(f"- {title} - {author}\n")
